



candidat_modif:
  path:     /modifcan
  defaults: { _controller: UserBundle:Candidat:updateinformation }







user_delete:
  path: /delete/{id}
  defaults: { _controller: UserBundle:User:deleteUser }

user_homepage:
  path:     /index
  defaults: { _controller: UserBundle:User:index }
candidat_homepagetest:
  path:     /access/candidat
  defaults: { _controller: UserBundle:Default:candidat  }
candidat:
  path:     /update
  defaults: { _controller: UserBundle:Candidat:updateinformation }
jury_homepagetest:
  path:     /access/jury
  defaults: { _controller: UserBundle:Default:jury  }
spectateur_homepage:
  path:     /access/spectateur
  defaults: { _controller: UserBundle:Default:spectateur  }
sponsor_homepage:
  path:     /access/sponsor
  defaults: { _controller: UserBundle:Default:sponsor  }
admin_homepage:
  path:     /admin
  defaults: { _controller: UserBundle:Default:admin  }
admin_affiche:
  path:     /affiche
  defaults: { _controller: UserBundle:User:afficher }
admin_voir_profil:
  path:     /voir/{id}
  defaults: { _controller: UserBundle:User:voirprofil }
admin_modifier:
  path:     /modif/{id}
  defaults: { _controller: UserBundle:User:update }

